name: frontend_mentor_planets_fact_site
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/json/data.json
  fonts:
    - family: Antonio
      fonts:
        - asset: lib/assets/fonts/Antonio-Medium.ttf
    - family: LeagueSpartan
      fonts:
        - asset: lib/assets/fonts/LeagueSpartan-Regular.ttf
        - asset: lib/assets/fonts/LeagueSpartan-Bold.ttf
          weight: 700
